import type {Route} from './+types/root';
import {useTranslation} from 'react-i18next';
import {isRouteErrorResponse, Links, Meta, Outlet, Scripts, ScrollRestoration} from 'react-router';
import {THEME_COLOR_DARK, THEME_COLOR_LIGHT} from './hooks/useTheme';

import './app.css';

export const links: Route.LinksFunction = () => {
  // Favicons + manifest are generated by the faviconRasters / webManifest Vite
  // plugins at build (stable names in the build root), referenced base-relative.
  const base = import.meta.env.BASE_URL;
  return [
    {rel: 'preconnect', href: 'https://fonts.googleapis.com'},
    {rel: 'preconnect', href: 'https://fonts.gstatic.com', crossOrigin: 'anonymous'},
    {
      rel: 'stylesheet',
      href: 'https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;0,9..144,500;1,9..144,300;1,9..144,400;1,9..144,500&family=Inter:wght@300;400;500;600;700&family=Space+Mono:wght@400;700&display=swap',
    },
    {rel: 'icon', type: 'image/svg+xml', href: `${base}favicon.svg`},
    {rel: 'icon', type: 'image/png', sizes: '96x96', href: `${base}favicon-96x96.png`},
    {rel: 'shortcut icon', href: `${base}favicon.ico`},
    {rel: 'apple-touch-icon', sizes: '180x180', href: `${base}apple-touch-icon.png`},
    {rel: 'manifest', href: `${base}site.webmanifest`},
  ];
};

// Pre-hydration bootstrap. Runs in <head> before stylesheets evaluate so the
// theme class is on <html> for the first paint (no FOUC). The design is
// light-primary: with no stored pref it defaults to LIGHT, but honours an
// explicit `prefers-color-scheme: dark`. Also adds `html.js` so no-js escape
// hatches deactivate, and syncs the mobile chrome theme-color.
// eslint-disable-next-line style/max-len
const themeBootstrap = `(function(){try{var k='rubynnn-portfolio:theme';var s=localStorage.getItem(k);var t=(s==='light'||s==='dark')?s:(window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');document.documentElement.classList.add(t,'js');var c=t==='dark'?'${THEME_COLOR_DARK}':'${THEME_COLOR_LIGHT}';document.querySelectorAll('meta[name="theme-color"]').forEach(function(m){m.setAttribute('content',c);});}catch(e){document.documentElement.classList.add('light','js');}})();`;

export function Layout({children}: {children: React.ReactNode}) {
  const {i18n} = useTranslation();
  return (
    <html lang={i18n.language} suppressHydrationWarning>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content={THEME_COLOR_LIGHT} media="(prefers-color-scheme: light)" />
        <meta name="theme-color" content={THEME_COLOR_DARK} media="(prefers-color-scheme: dark)" />
        <script
          // eslint-disable-next-line react/dom-no-dangerously-set-innerhtml
          dangerouslySetInnerHTML={{__html: themeBootstrap}}
        />
        <Meta />
        <Links />
      </head>
      <body suppressHydrationWarning>
        {children}
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

export default function App() {
  return <Outlet />;
}

export function ErrorBoundary({error}: Route.ErrorBoundaryProps) {
  const {t} = useTranslation();
  const isRouteError = isRouteErrorResponse(error);
  const is404 = isRouteError && error.status === 404;
  const title = is404 ? t('error.not_found_title') : t('error.title');
  const sub = is404 ? t('error.not_found_sub') : t('error.sub');
  const isDev = import.meta.env.DEV;
  const details = isDev && error instanceof Error ? error.message : undefined;

  return (
    <main className="mx-auto flex min-h-dvh max-w-2xl flex-col items-center justify-center px-6 text-center">
      <p className="font-mono text-2xs uppercase tracking-[0.2em] text-accent">{is404 ? '404' : 'error'}</p>
      <h1 className="mt-4 font-display text-5xl font-light italic tracking-tight md:text-6xl">{title}</h1>
      <p className="mt-4 max-w-md text-muted">{sub}</p>
      {details != null && <p className="mt-4 font-mono text-xs text-faint">{details}</p>}
      <a href="/" className="mt-8 inline-flex items-center gap-2 font-mono text-sm uppercase tracking-[0.14em] text-accent hover:underline">
        <span aria-hidden>→</span> {t('error.home')}
      </a>
    </main>
  );
}
